api_platform:
  title: Test
  version: 1.0
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  use_symfony_listeners: true
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
