services:
  postgres:
    image: postgres:16
    container_name: postgres-secure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - "7654:5432"
