services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9070:80"
    volumes:
      - "./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/project/public"
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    volumes:
      - "./:/var/www/project"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "7536:5432"
